### ISSUE TITLE
Red highlights in Tutorials not visible in dark theme

### ISSUE THREAD

**Issue by CJGits** [AnyBody/tutorials#12]
The red highlights used in the tutorials are not visible in the dark theme. See screenshots below from .../A_Getting_started_modeling/lesson3.html

![Example light theme](https://github.com/AnyBody/tutorials/assets/75834225/6d1e7cf2-8c55-47dd-b6e4-010609a10a4f)

![Example dark theme](https://github.com/AnyBody/tutorials/assets/75834225/335e801f-1fd3-45d0-b0d5-4e9bbc90ceec)

**Comment by melund** [comment]
@CJGits, Thanks a ton for pointing this out. I have fixed this #15. 

![image](https://github.com/AnyBody/tutorials/assets/1038978/ea9170ef-3e41-4365-b514-d4d5d114d1a2)

It should be released with the next version of AnyBody later today.
