### ISSUE TITLE
code highlighting not correct when dark mode is on

### ISSUE THREAD

**Issue by bkje14** [AnyBody/tutorials#16]
The pygments_anyscript highlighter does not show the code inside `§` tags as red when dark mode is on. They become white.
Classnames also become styled as comments in darkmode

![Screenshot 2024-08-07 080256](https://github.com/user-attachments/assets/a34e9b89-8d41-4c75-afca-e47ce79752fe)
![Screenshot 2024-08-07 080243](https://github.com/user-attachments/assets/7e311e90-9c66-4b5f-a1f4-bdb9d7cc96a9)

**Comment by melund** [comment]
This is fixed in our online version
